spring:
  application:
    name: alumni-backend
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/sslcommerz
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345678}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true